config/routes.rb
Rails.application.routes.draw do
  resources :shops, only: :index do
    scope module: :shops do
      resources :opening_hours, only: :index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/opening_hour.rb
class OpeningHour < ApplicationRecord
  enum day: {
    monday:    'monday',
    tuesday:   'tuesday',
    wednesday: 'wednesday',
    thursday:  'thursday',
    friday:    'friday',
    saturday:  'saturday',
    sunday:    'sunday'
  }

  belongs_to :shop

  validates :day, presence: true

  with_options unless: :day_off? do
    validates :opening, presence: true
    validates :closing, presence: true, comparison: { greater_than: :opening }
  end

  def working_day
    WorkingDay.new(day)
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :opening_hours, dependent: :destroy
end

app/models/working_day.rb
class WorkingDay
  include ActiveModel::Conversion
  include Comparable

  attr_accessor :opening_hours
  attr_reader :index, :name

  def self.all
    Date::DAYNAMES.map do |day_name|
      new(day_name)
    end
  end

  def initialize(name)
    @name = name.downcase

    @index = Date::DAYNAMES.find_index do |day_name|
      day_name.downcase == @name
    end
  end

  def <=>(other)
    index <=> other.index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/shop_scoped.rb
module ShopScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_shop
  end

  private

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end
end

app/controllers/shops/opening_hours_controller.rb
class Shops::OpeningHoursController < ApplicationController
  include ShopScoped

  def index
    @working_days = WorkingDay.all.rotate(Date.current.cwday)
    @working_days.each do |working_day|
      working_day.opening_hours = @shop.opening_hours.filter do |opening_hour|
        opening_hour.working_day == working_day
      end
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops/opening_hours_helper.rb
module Shops::OpeningHoursHelper
  def opening_hour_to_human(opening_hour)
    [
      l(opening_hour.opening, format: '%H:%M'),
      l(opening_hour.closing, format: '%H:%M')
    ].join('-')
  end
end

app/helpers/shops/working_days_helper.rb
module Shops::WorkingDaysHelper
  def working_day_to_human(working_day)
    t('date.day_names')[working_day.index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZeCollectionneur</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/_shop.html.erb
<li><%= link_to shop.name, shop_opening_hours_path(shop) %></li>

app/views/shops/index.html.erb
<h1>Shop list</h1>
<ul>
  <%= render @shops %>
</ul>

app/views/shops/opening_hours/_opening_hour.html.erb
<% if opening_hour.day_off? %>
  <%= "Fermé" %>
<% else %>
  <%= opening_hour_to_human(opening_hour) %>
<% end %>

app/views/shops/opening_hours/index.html.erb
<h1><%= @shop.name %></h1>

<h2>Horaires</h2>

<table>
  <tbody>
    <%= render @working_days %>
  </tbody>
</table>

app/views/shops/working_days/_working_day.html.erb
<tr class="<%= class_names('font-bold': working_day_counter.zero?) %>">
  <td><%= working_day_to_human working_day %></td>
  <td><%= render working_day.opening_hours %></td>
</tr>